# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_codes',
        ),
        migrations.AddField(
            model_name='grade',
            name='classgroup',
            field=models.ForeignKey(help_text='The class the grade was given in', null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.classgroup'),
        ),
    ]
