# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='class_code',
            field=models.CharField(help_text="The class group's unique identifier code.", max_length=10),
        ),
    ]
