# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170613_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grademethod',
            old_name='values',
            new_name='vals',
        ),
    ]
