# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20171102_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='baseline_grade',
            field=models.ForeignKey(blank=True, help_text='The grade attained \tby the student in baseline testing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BL', to='analysis.gradeValue'),
        ),
    ]
