# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_grade_baseline_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.CharField(choices=[('PA', 'Persistent Absence'), ('AC', 'Attendance Concern'), ('EA', 'Expected Attendance'), ('FA', 'Full Attendance')], default='EA', help_text='The level of attendance the \tstudent has attained so far this school year', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='guest_status',
            field=models.BooleanField(default=False, help_text='Whether the student is a guest \tpupil at the school'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_status',
            field=models.CharField(choices=[('N', 'N/A'), ('T', 'Traveller')], default='N', help_text='The home grouping the student\t belongs to', max_length=1),
        ),
    ]
