# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170620_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ebacc_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.CharField(blank=True, help_text='The faculty the subject is part of.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='option_subject',
            field=models.BooleanField(default=True),
        ),
    ]
