# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20180115_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='banding',
        ),
        migrations.AddField(
            model_name='student',
            name='narrow_banding',
            field=models.CharField(choices=[('Hx', 'Extremely High Ability'), ('H', 'Upper/High Ability'), ('Mh', 'Middle Ability, Higher division'), ('M', 'Middle Ability'), ('Ml', 'Middle Ability, Lower division'), ('L', 'Lower Ability'), ('Lx', 'Extremely Low Ability'), ('N', 'No data')], default='N', help_text='The finer ability grouping the student belongs to.', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='wide_banding',
            field=models.CharField(choices=[('H', 'Upper/High Ability'), ('M', 'Middle Ability'), ('L', 'Lower Ability'), ('N', 'No data')], default='N', help_text='The wider ability grouping the student belongs to.', max_length=1),
        ),
    ]
