# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20170714_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='id',
            field=models.CharField(help_text='The datadrop and student \tupn the headline measures are linked to.', max_length=43, primary_key=True, serialize=False),
        ),
    ]
