# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20180118_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradevalue',
            name='whole_grade',
            field=models.ForeignKey(help_text='The whole grade this subgrade refers to. Can be self.', null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.gradeValue'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='ebacc_achieved_std',
            field=models.BooleanField(default=False, help_text='Whether the student achieved the EBacc (standard grade) or \t\tnot.'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='ebacc_achieved_stg',
            field=models.BooleanField(default=False, help_text='Whether the student achieved the EBacc (strong grade) or \t\tnot.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='attainment8bucket',
            field=models.CharField(choices=[('en', 'English'), ('ma', 'Maths'), ('eb', 'Ebacc'), ('op', 'Open')], help_text='The highest Attainment 8 bucket the subject can be counted \t\tin.', max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tags',
            field=models.ManyToManyField(help_text='Set of tags linking \tsubject to other subjects across yeargroups', to='analysis.subjectTag'),
        ),
    ]
