# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20170714_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='att8_progress',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The difference in Attainment 8 score between this datadrop\t\t and baseline.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='headline',
            name='attainment8',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The Attainment8 calculated for the student/DD.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='headline',
            name='eb_att8',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The score for the EBacc Att8 bucket.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='headline',
            name='en_att8',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The score for the English Att8 bucket.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='headline',
            name='ma_att8',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The score for the Maths Att8 bucket.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='headline',
            name='op_att8',
            field=models.DecimalField(decimal_places=1, default=0, help_text='The score for the Open Att8 bucket.', max_digits=3),
        ),
    ]
