# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20180309_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='focusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the focus group.', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='focus_groups',
            field=models.ManyToManyField(help_text='The focus groups the student belongs to.', to='analysis.focusGroup'),
        ),
    ]
