# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20170725_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='ebacc_achieved',
        ),
        migrations.AddField(
            model_name='headline',
            name='ebacc_achieved_std',
            field=models.BooleanField(default=False, help_text='Whether the student achieved the EBacc (standard grade) or not.'),
        ),
        migrations.AddField(
            model_name='headline',
            name='ebacc_achieved_stg',
            field=models.BooleanField(default=False, help_text='Whether the student achieved the EBacc (strong grade) or not.'),
        ),
    ]
