# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20170926_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='progress',
            field=models.IntegerField(blank=True, default=None, help_text='The progress the student has made from their baseline.'),
        ),
    ]
