# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20171020_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='progress',
            field=models.IntegerField(blank=True, help_text='The progress the student has made from their baseline.'),
        ),
    ]
