# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20171020_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='EAPgrade',
            field=models.ForeignKey(blank=True, help_text='The estimated attainment for the student in this data drop.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EAP', to='analysis.gradeValue'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='progress',
            field=models.IntegerField(blank=True, help_text='The progress the student has made from their baseline.', null=True),
        ),
    ]
